# Generated by Django 4.2.10 on 2024-02-10 21:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('wish_price', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Wunschpreis')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert am')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='FV-Mitglied')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Vor- und Nachname')),
                ('matriculation_number', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Matrikelnummer')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Betrag')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='FV-Mitglied')),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.offer')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.seller', verbose_name='Verkäufer:in')),
            ],
        ),
    ]
