# Generated by Django 4.2.10 on 2024-02-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_offer_location_offer_marked_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='wish_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Wunschpreis'),
        ),
    ]
