# Generated by Django 4.2.10 on 2024-02-14 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_offer_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='is_active',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='wish_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='matriculation_number',
            new_name='matriculationNumber',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='offer_id',
        ),
        migrations.AddField(
            model_name='offer',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='search.seller', verbose_name='Verkäufer:in'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='search.offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='location',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Lagerort'),
        ),
    ]
