# Generated by Django 4.2.10 on 2024-02-14 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_rename_created_at_offer_createdat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='isActive',
            new_name='active',
        ),
    ]
