# Generated by Django 4.2.10 on 2024-02-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_book_exammodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.DeleteModel(
            name='ExamModel',
        ),
        migrations.AlterField(
            model_name='book',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.exam', verbose_name='Prüfung'),
        ),
    ]
