# Generated by Django 4.2.10 on 2024-02-20 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_exam_delete_exammodel_alter_book_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.book', verbose_name='ISBN'),
        ),
    ]
