# Generated by Django 4.2.10 on 2024-02-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_remove_book_id_alter_book_isbn_alter_offer_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='member',
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name'),
        ),
    ]
