# Generated by Django 4.2.10 on 2024-02-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_rename_isbn_offer_book_offer_member_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.exam', verbose_name='Prüfung'),
        ),
    ]
