# Generated by Django 4.2.10 on 2024-02-26 15:51

from django.db import migrations, models
import search.validators


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_offer_note_seller_note_alter_book_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, validators=[search.validators.validate_isbn_numeric], verbose_name='ISBN'),
        ),
    ]
