# Generated by Django 4.2.10 on 2024-02-26 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='matriculationNumber',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Matrikelnummer'),
        ),
    ]
