# Generated by Django 4.2.10 on 2024-02-26 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_alter_seller_matriculationnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='matriculationNumber',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Matrikelnummer'),
        ),
    ]
