# Generated by Django 4.2.10 on 2024-02-29 19:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0016_alter_seller_matriculationnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSeller',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255, verbose_name='Vor- und Nachname')),
                ('matriculationNumber', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Matrikelnummer')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='E-Mail')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Anmerkung')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical seller',
                'verbose_name_plural': 'historical sellers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
