# Generated by Django 4.2.10 on 2024-03-03 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_historicalseller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='member',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='modified',
        ),
    ]
